(function() {var implementors = {
"bitcoin_internals":[["impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"bitcoin_internals/hex/buf_encoder/struct.OutBytes.html\" title=\"struct bitcoin_internals::hex::buf_encoder::OutBytes\">OutBytes</a>",1,["bitcoin_internals::hex::buf_encoder::out_bytes::OutBytes"]]],
"bitvec":[["impl&lt;T = <a class=\"primitive\" href=\"https://doc.rust-lang.org/1.78.0/std/primitive.usize.html\">usize</a>, O = <a class=\"struct\" href=\"bitvec/order/struct.Lsb0.html\" title=\"struct bitvec::order::Lsb0\">Lsb0</a>&gt; !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"bitvec/slice/struct.BitSlice.html\" title=\"struct bitvec::slice::BitSlice\">BitSlice</a>&lt;T, O&gt;",1,["bitvec::slice::BitSlice"]]],
"bstr":[["impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"bstr/struct.BStr.html\" title=\"struct bstr::BStr\">BStr</a>",1,["bstr::bstr::BStr"]]],
"bytes":[["impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"bytes/buf/struct.UninitSlice.html\" title=\"struct bytes::buf::UninitSlice\">UninitSlice</a>",1,["bytes::buf::uninit_slice::UninitSlice"]]],
"hex_conservative":[["impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"hex_conservative/buf_encoder/struct.OutBytes.html\" title=\"struct hex_conservative::buf_encoder::OutBytes\">OutBytes</a>",1,["hex_conservative::buf_encoder::out_bytes::OutBytes"]]],
"indexmap":[["impl&lt;K, V&gt; !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"indexmap/map/struct.Slice.html\" title=\"struct indexmap::map::Slice\">Slice</a>&lt;K, V&gt;",1,["indexmap::map::slice::Slice"]],["impl&lt;T&gt; !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"indexmap/set/struct.Slice.html\" title=\"struct indexmap::set::Slice\">Slice</a>&lt;T&gt;",1,["indexmap::set::slice::Slice"]]],
"no_std_compat":[],
"serde_bytes":[["impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"serde_bytes/struct.Bytes.html\" title=\"struct serde_bytes::Bytes\">Bytes</a>",1,["serde_bytes::bytes::Bytes"]]],
"serde_json":[["impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"serde_json/value/struct.RawValue.html\" title=\"struct serde_json::value::RawValue\">RawValue</a>",1,["serde_json::raw::RawValue"]]],
"tikv_jemalloc_ctl":[["impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"tikv_jemalloc_ctl/struct.Name.html\" title=\"struct tikv_jemalloc_ctl::Name\">Name</a>",1,["tikv_jemalloc_ctl::keys::Name"]]],
"wasmparser":[["impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/1.78.0/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> for <a class=\"struct\" href=\"wasmparser/types/struct.KebabStr.html\" title=\"struct wasmparser::types::KebabStr\">KebabStr</a>",1,["wasmparser::validator::types::KebabStr"]]],
"wasmtime_environ":[]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()