[workspace]
resolver = "2"

members = ["cli", "core"]

[workspace.package]
version = "0.10.1"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate's programmatic testing framework."
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/paritytech/try-runtime-cli"
repository = "https://github.com/paritytech/try-runtime-cli/"

[workspace.dependencies]
# Reminder: "~a.b" means >= a.b.0, < a.(b + 1).0
array-bytes = { version = "~9.3" }
assert_cmd = { version = "~2.1" }
async-trait = { version = "~0.1" }
bytesize = { version = "~2.3" }
clap = { version = "~4.5" }
env_logger = { version = "~0.11" }
hex = { version = "0.4.3", default-features = false }
itertools = { version = "~0.14" }
log = { version = "~0.4.29" }
parity-scale-codec = { version = "~3.7" }
regex = { version = "~1.12" }
serde = { version = "~1.0" }
serde_json = { version = "~1.0" }
strum = "~0.27"
strum_macros = "~0.27"
tempfile = { version = "~3.24" }
tokio = { version = "~1.49" }
zstd = { version = "~0.13", default-features = false }

# Integration test-only dependency.
# Across the whole workspace, it is used solely as a dev dependency; thus it may be pinned to a git revision
# without impacting publication to crates.io .
substrate-cli-test-utils = { git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }

# Polkadot SDK (master @ e1c5425b23f1, 2026-05-29)
frame-remote-externalities = { version = "~0.35", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }
frame-try-runtime = { version = "~0.34", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }
frame-support = { version = "~28.0", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }
frame-system = { version = "~28.0", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }

sc-cli = { version = "~0.36", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1", default-features = false }
sc-executor = { version = "~0.32", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }
sc-service = { version = "~0.35", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }

sp-api = { version = "~26.0", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }
sp-consensus-aura = { version = "~0.32", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }
sp-consensus-babe = { version = "~0.32", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }
sp-core = { version = "~28.0", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }
sp-crypto-hashing = { version = "~0.1", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }
sp-externalities = { version = "~0.25", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }
sp-inherents = { version = "~26.0", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }
sp-io = { version = "~30.0", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }
sp-keystore = { version = "~0.34", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }
sp-rpc = { version = "~26.0", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }
sp-runtime = { version = "~31.0", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }
sp-state-machine = { version = "~0.35", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }
sp-storage = { version = "~19.0", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }
sp-std = { version = "~14.0", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }
sp-timestamp = { version = "~26.0", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }
sp-transaction-storage-proof = { version = "~26.0", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }
sp-version = { version = "~29.0", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }
sp-weights = { version = "~27.0", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }

substrate-rpc-client = { version = "~0.33", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }

polkadot-primitives = { version = "~7.0", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }
cumulus-primitives-parachain-inherent = { version = "~0.7", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }
cumulus-primitives-core = { version = "~0.7", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }
cumulus-client-parachain-inherent = { version = "~0.1", git = "https://github.com/paritytech/polkadot-sdk", rev = "e1c5425b23f1" }

# Local
try-runtime-core = { path = "core" }


