edition = "2021"

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true

# Consistency
newline_style = "Unix"

# Format comments
comment_width = 100
wrap_comments = true
