name: Rust checks

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  rust-checks:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1

      - name: Install clippy and fmt
        run: rustup component add clippy rustfmt

      - name: Run Format Checks
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all

      - name: Run Linter
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets -- --no-deps -D warnings

      - name: Run Unit Test Suite
        uses: actions-rs/cargo@v1
        with:
          command: test
